mysql -u root -psafestsystemever -e "DROP DATABASE IF EXISTS WEBLOGS;
CREATE DATABASE WEBLOGS;
USE WEBLOGS;
DROP TABLE IF EXISTS SMALL_LOGS;
CREATE TABLE SMALL_LOGS(
L_Id INT NOT NULL AUTO_INCREMENT,
Log_Date DATE,
Log_Time VARCHAR(20),
Log_Path VARCHAR(20),
Log_Type VARCHAR(10),
Log_Webfile VARCHAR(120),
Log_Number1 INT,
Log_IPAddress VARCHAR(50),
Log_Number2 INT,
Log_Number3 INT,
Log_Systembit INT,
Log_Number4 INT,
PRIMARY KEY(L_Id));"